### ISSUE TITLE
Metrics

### ISSUE THREAD

**Issue by marcosci** [marcosci/NLMR#10]
Implement more metric functions

- Fractal dimension
- Hurst 
- Lacunarity
- ... ?

**Comment by csim063** [comment]
Useful paper to get thinking about which metrics may be most useful. https://www.sciencedirect.com/science/article/pii/S1470160X07001306

**Comment by marcosci** [comment]
* Proportion of landscape
* Number of instances 
* Instance size distribution
* Instance perimeter
* Instance bounding box aspect-ratio and proportion of bounding box area
* Instance edge contrast index
* Total edge

> Slager CTJ, De Vries B. 2013. Landscape generator: Method to generate landscape configurations for spatial plan-making. Computers, Environment and Urban Systems 39:1–11. Elsevier Ltd.

**Comment by marcosci** [comment]
to be continued there: [https://github.com/marcosci/landscapemetrics/issues/1](https://github.com/marcosci/landscapemetrics/issues/1)
