### ISSUE TITLE
nlm_randomcluster -> nlm_neigh

### ISSUE THREAD

**Issue by marcosci** [marcosci/NLMR#24]
https://github.com/ropensci/onboarding/issues/188#issuecomment-368042693:

The neighbourhood input is an integer here, whereas it was method names in nlm_neigh. It would be helpful to unify this (and the spelling of neighbourhood - one US, one British English). My preference would be the numbers, because I always forget the names and it's less to type!

**Comment by Z3tt** [comment]
I would suggest an input called "neigh" or smt similar instead of having two version for both types of spelling.
